site_name: "MeshExpert Live! Documentation"
site_url: http://www.datamesh.com
site_description: A Mixed-Reality Show Product.
repo_url: https://github.com/michael2008/ME-Live-Doc
copyright: "Copyright (C) 2016-2017 DataMesh Inc."
docs_dir: docs
theme: 'material'

pages:
    - 'Home': 'index.md'
    - 'Getting Started': 'model.md'
    - 'Source Configuration': 'source-configuration.md'

# Options
extra:
  logo: 'images/datamesh.png'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/datameshar'

markdown_extensions:
    - admonition: